pipeline {
    environment {
        BUILDDIR = 'cmake-build-debug'
    }
    agent {
        docker { image 'fsfw-ci:d2'}
    }
    stages {
        stage('Clean') {
            steps {
                sh 'rm -rf $BUILDDIR'
            }
        }
        stage('Configure') {
            steps {
                dir(BUILDDIR) {
                    sh 'cmake -DFSFW_OSAL=host ..'
                }
            }
        }
        stage('Build') {
            steps {
                dir(BUILDDIR) {
                    sh 'cmake --build . -j4'
                }
            }
        }
    }
}
